# -*- coding: utf-8 -*-
if __name__ == "__main__":
    import _in_folder_tools

import basis.with_pydoris
import basis.basis_function
import basis.HuShunGuPiao_function
import basis.with_pydoris
import pandas

# https://tushare.pro/document/2?doc_id=79
# 默认的调取接口必须指定ts_code，在默认接口后加_vip则无需指定ts_code。
# *_vip接口需要5000积分才可调用。具体见上面链接。


# 创建表格
def create_table():
    # 连接database
    doris_client = basis.with_pydoris.connect_database()
    # 读取basis/config.yaml
    config = basis.basis_function.load_config()
    # 创建表格
    operation = (
        "CREATE TABLE IF NOT EXISTS "
        + config["database_name"]
        + "."
        + config["Ts_HuShenGuPiao_CaiWuShuJu_CaiWuZhiBiaoShuJu"]["table_name"]
        + """
        (
            ts_code VARCHAR(50) COMMENT "TS代码",
            ann_date VARCHAR(8) COMMENT "公告日期",
            end_date VARCHAR(8) COMMENT "报告期",
            eps DECIMAL COMMENT "基本每股收益",
            dt_eps DECIMAL COMMENT "稀释每股收益",
            total_revenue_ps DECIMAL COMMENT "每股营业总收入",
            revenue_ps DECIMAL COMMENT "每股营业收入",
            capital_rese_ps DECIMAL COMMENT "每股资本公积",            
            surplus_rese_ps DECIMAL COMMENT "每股盈余公积",
            undist_profit_ps DECIMAL COMMENT "每股未分配利润",
            extra_item DECIMAL COMMENT "非经常性损益",
            profit_dedt DECIMAL COMMENT "扣除非经常性损益后的净利润",
            gross_margin DECIMAL COMMENT "毛利",
            current_ratio DECIMAL COMMENT "流动比率",
            quick_ratio DECIMAL COMMENT "速动比率",
            cash_ratio DECIMAL COMMENT "保守速动比率",
            invturn_days DECIMAL COMMENT "存货周转天数",
            arturn_days DECIMAL COMMENT "应收账款周转天数",
            inv_turn DECIMAL COMMENT "存货周转率",
            ar_turn DECIMAL COMMENT "应收账款周转率",
            ca_turn DECIMAL COMMENT "流动资产周转率",
            fa_turn DECIMAL COMMENT "固定资产周转率",
            assets_turn DECIMAL COMMENT "总资产周转率",
            op_income DECIMAL COMMENT "经营活动净收益",
            valuechange_income DECIMAL COMMENT "价值变动净收益",
            interst_income DECIMAL COMMENT "利息费用",
            daa DECIMAL COMMENT "折旧与摊销",
            ebit DECIMAL COMMENT "息税前利润",
            ebitda DECIMAL COMMENT "息税折旧摊销前利润",
            fcff DECIMAL COMMENT "企业自由现金流量",
            fcfe DECIMAL COMMENT "股权自由现金流量",
            current_exint DECIMAL COMMENT "无息流动负债",
            noncurrent_exint DECIMAL COMMENT "无息非流动负债",
            interestdebt DECIMAL COMMENT "带息债务",
            netdebt DECIMAL COMMENT "净债务",
            tangible_asset DECIMAL COMMENT "有形资产",
            working_capital DECIMAL COMMENT "营运资金",
            networking_capital DECIMAL COMMENT "营运流动资本",
            invest_capital DECIMAL COMMENT "全部投入资本",
            retained_earnings DECIMAL COMMENT "留存收益",
            diluted2_eps DECIMAL COMMENT "期末摊薄每股收益",
            bps DECIMAL COMMENT "每股净资产",
            ocfps DECIMAL COMMENT "每股经营活动产生的现金流量净额",
            retainedps DECIMAL COMMENT "每股留存收益",
            cfps DECIMAL COMMENT "每股现金流量净额",
            ebit_ps DECIMAL COMMENT "每股息税前利润",
            fcff_ps DECIMAL COMMENT "每股企业自由现金流量",
            fcfe_ps DECIMAL COMMENT "每股股东自由现金流量",
            netprofit_margin DECIMAL COMMENT "销售净利率",
            grossprofit_margin DECIMAL COMMENT "销售毛利率",
            cogs_of_sales DECIMAL COMMENT "销售成本率",
            expense_of_sales DECIMAL COMMENT "销售期间费用率",
            profit_to_gr DECIMAL COMMENT "净利润/营业总收入",
            saleexp_to_gr DECIMAL COMMENT "销售费用/营业总收入",
            adminexp_of_gr DECIMAL COMMENT "管理费用/营业总收入",
            finaexp_of_gr DECIMAL COMMENT "财务费用/营业总收入",
            impai_ttm DECIMAL COMMENT "资产减值损失/营业总收入",
            gc_of_gr DECIMAL COMMENT "营业总成本/营业总收入",
            op_of_gr DECIMAL COMMENT "营业利润/营业总收入",
            ebit_of_gr DECIMAL COMMENT "息税前利润/营业总收入",
            roe DECIMAL COMMENT "净资产收益率",
            roe_waa DECIMAL COMMENT "加权平均净资产收益率",
            roe_dt DECIMAL COMMENT "净资产收益率(扣除非经常损益)",
            roa DECIMAL COMMENT "总资产报酬率",
            npta DECIMAL COMMENT "总资产净利润",
            roic DECIMAL COMMENT "投入资本回报率",
            roe_yearly DECIMAL COMMENT "年化净资产收益率",
            roa2_yearly DECIMAL COMMENT "年化总资产报酬率",
            roe_avg DECIMAL COMMENT "平均净资产收益率(增发条件)",
            opincome_of_ebt DECIMAL COMMENT "经营活动净收益/利润总额",
            investincome_of_ebt DECIMAL COMMENT "价值变动净收益/利润总额",
            n_op_profit_of_ebt DECIMAL COMMENT "营业外收支净额/利润总额",
            tax_to_ebt DECIMAL COMMENT "所得税/利润总额",
            dtprofit_to_profit DECIMAL COMMENT "扣除非经常损益后的净利润/净利润",
            salescash_to_or DECIMAL COMMENT "销售商品提供劳务收到的现金/营业收入",
            ocf_to_or DECIMAL COMMENT "经营活动产生的现金流量净额/营业收入",
            ocf_to_opincome DECIMAL COMMENT "经营活动产生的现金流量净额/经营活动净收益",
            capitalized_to_da DECIMAL COMMENT "资本支出/折旧和摊销",
            debt_to_assets DECIMAL COMMENT "资产负债率",
            assets_to_eqt DECIMAL COMMENT "权益乘数",
            dp_assets_to_eqt DECIMAL COMMENT "权益乘数(杜邦分析)",
            ca_to_assets DECIMAL COMMENT "流动资产/总资产",
            nca_to_assets DECIMAL COMMENT "非流动资产/总资产",
            tbassets_to_totalassets DECIMAL COMMENT "有形资产/总资产",
            int_to_talcap DECIMAL COMMENT "带息债务/全部投入资本",
            eqt_to_talcapital DECIMAL COMMENT "归属于母公司的股东权益/全部投入资本",
            currentdebt_to_debt DECIMAL COMMENT "流动负债/负债合计",
            longdeb_to_debt DECIMAL COMMENT "非流动负债/负债合计",
            ocf_to_shortdebt DECIMAL COMMENT "经营活动产生的现金流量净额/流动负债",
            debt_to_eqt DECIMAL COMMENT "产权比率",
            eqt_to_debt DECIMAL COMMENT "归属于母公司的股东权益/负债合计",
            eqt_to_interestdebt DECIMAL COMMENT "归属于母公司的股东权益/带息债务",
            tangibleasset_to_debt DECIMAL COMMENT "有形资产/负债合计",
            tangasset_to_intdebt DECIMAL COMMENT "有形资产/带息债务",
            tangibleasset_to_netdebt DECIMAL COMMENT "有形资产/净债务",
            ocf_to_debt DECIMAL COMMENT "经营活动产生的现金流量净额/负债合计",
            ocf_to_interestdebt DECIMAL COMMENT "经营活动产生的现金流量净额/带息债务",
            ocf_to_netdebt DECIMAL COMMENT "经营活动产生的现金流量净额/净债务",
            ebit_to_interest DECIMAL COMMENT "已获利息倍数(EBIT/利息费用)",
            longdebt_to_workingcapital DECIMAL COMMENT "长期债务与营运资金比率",
            ebitda_to_debt DECIMAL COMMENT "息税折旧摊销前利润/负债合计",
            turn_days DECIMAL COMMENT "营业周期",
            roa_yearly DECIMAL COMMENT "年化总资产净利率",
            roa_dp DECIMAL COMMENT "总资产净利率(杜邦分析)",
            fixed_assets DECIMAL COMMENT "固定资产合计",
            profit_prefin_exp DECIMAL COMMENT "扣除财务费用前营业利润",
            non_op_profit DECIMAL COMMENT "非营业利润",
            op_to_ebt DECIMAL COMMENT "营业利润／利润总额",
            nop_to_ebt DECIMAL COMMENT "非营业利润／利润总额",
            ocf_to_profit DECIMAL COMMENT "经营活动产生的现金流量净额／营业利润",
            cash_to_liqdebt DECIMAL COMMENT "货币资金／流动负债",
            cash_to_liqdebt_withinterest DECIMAL COMMENT "货币资金／带息流动负债",
            op_to_liqdebt DECIMAL COMMENT "营业利润／流动负债",
            op_to_debt DECIMAL COMMENT "营业利润／负债合计",
            roic_yearly DECIMAL COMMENT "年化投入资本回报率",
            total_fa_trun DECIMAL COMMENT "固定资产合计周转率",
            profit_to_op DECIMAL COMMENT "利润总额／营业收入",
            q_opincome DECIMAL COMMENT "经营活动单季度净收益",
            q_investincome DECIMAL COMMENT "价值变动单季度净收益",
            q_dtprofit DECIMAL COMMENT "扣除非经常损益后的单季度净利润",
            q_eps DECIMAL COMMENT "每股收益(单季度)",
            q_netprofit_margin DECIMAL COMMENT "销售净利率(单季度)",
            q_gsprofit_margin DECIMAL COMMENT "销售毛利率(单季度)",
            q_exp_to_sales DECIMAL COMMENT "销售期间费用率(单季度)",
            q_profit_to_gr DECIMAL COMMENT "净利润／营业总收入(单季度)",
            q_saleexp_to_gr DECIMAL COMMENT "销售费用／营业总收入 (单季度)",
            q_adminexp_to_gr DECIMAL COMMENT "管理费用／营业总收入 (单季度)",
            q_finaexp_to_gr DECIMAL COMMENT "财务费用／营业总收入 (单季度)",
            q_impair_to_gr_ttm DECIMAL COMMENT "资产减值损失／营业总收入(单季度)",
            q_gc_to_gr DECIMAL COMMENT "营业总成本／营业总收入 (单季度)",
            q_op_to_gr DECIMAL COMMENT "营业利润／营业总收入(单季度)",
            q_roe DECIMAL COMMENT "净资产收益率(单季度)",
            q_dt_roe DECIMAL COMMENT "净资产单季度收益率(扣除非经常损益)",
            q_npta DECIMAL COMMENT "总资产净利润(单季度)",
            q_opincome_to_ebt DECIMAL COMMENT "经营活动净收益／利润总额(单季度)",
            q_investincome_to_ebt DECIMAL COMMENT "价值变动净收益／利润总额(单季度)",
            q_dtprofit_to_profit DECIMAL COMMENT "扣除非经常损益后的净利润／净利润(单季度)",
            q_salescash_to_or DECIMAL COMMENT "销售商品提供劳务收到的现金／营业收入(单季度)",
            q_ocf_to_sales DECIMAL COMMENT "经营活动产生的现金流量净额／营业收入(单季度)",
            q_ocf_to_or DECIMAL COMMENT "经营活动产生的现金流量净额／经营活动净收益(单季度)",
            basic_eps_yoy DECIMAL COMMENT "基本每股收益同比增长率(%)",
            dt_eps_yoy DECIMAL COMMENT "稀释每股收益同比增长率(%)",
            cfps_yoy DECIMAL COMMENT "每股经营活动产生的现金流量净额同比增长率(%)",
            op_yoy DECIMAL COMMENT "营业利润同比增长率(%)",
            ebt_yoy DECIMAL COMMENT "利润总额同比增长率(%)",
            netprofit_yoy DECIMAL COMMENT "归属母公司股东的净利润同比增长率(%)",
            dt_netprofit_yoy DECIMAL COMMENT "归属母公司股东的净利润-扣除非经常损益同比增长率(%)",
            ocf_yoy DECIMAL COMMENT "经营活动产生的现金流量净额同比增长率(%)",
            roe_yoy DECIMAL COMMENT "净资产收益率(摊薄)同比增长率(%)",
            bps_yoy DECIMAL COMMENT "每股净资产相对年初增长率(%)",
            assets_yoy DECIMAL COMMENT "资产总计相对年初增长率(%)",
            eqt_yoy DECIMAL COMMENT "归属母公司的股东权益相对年初增长率(%)",
            tr_yoy DECIMAL COMMENT "营业总收入同比增长率(%)",
            or_yoy DECIMAL COMMENT "营业收入同比增长率(%)",
            q_gr_yoy DECIMAL COMMENT "营业总收入同比增长率(%)(单季度)",
            q_gr_qoq DECIMAL COMMENT "营业总收入环比增长率(%)(单季度)",
            q_sales_yoy DECIMAL COMMENT "营业收入同比增长率(%)(单季度)",
            q_sales_qoq DECIMAL COMMENT "营业收入环比增长率(%)(单季度)",
            q_op_yoy DECIMAL COMMENT "营业利润同比增长率(%)(单季度)",
            q_op_qoq DECIMAL COMMENT "营业利润环比增长率(%)(单季度)",
            q_profit_yoy DECIMAL COMMENT "净利润同比增长率(%)(单季度)",
            q_profit_qoq DECIMAL COMMENT "净利润环比增长率(%)(单季度)",
            q_netprofit_yoy DECIMAL COMMENT "归属母公司股东的净利润同比增长率(%)(单季度)",
            q_netprofit_qoq DECIMAL COMMENT "归属母公司股东的净利润环比增长率(%)(单季度)",
            equity_yoy DECIMAL COMMENT "净资产同比增长率",
            rd_exp DECIMAL COMMENT "研发费用",
            update_flag VARCHAR(1) COMMENT "更新标识",                    
        )
        UNIQUE KEY(
                ts_code,
                ann_date,
                end_date,
                eps,
                dt_eps,
                total_revenue_ps,
                revenue_ps,
                capital_rese_ps,
                surplus_rese_ps,
                undist_profit_ps,
                extra_item,
                profit_dedt,
                gross_margin,
                current_ratio,
                quick_ratio,
                cash_ratio,
                invturn_days,
                arturn_days,
                inv_turn,
                ar_turn,
                ca_turn,
                fa_turn,
                assets_turn,
                op_income,
                valuechange_income,
                interst_income,
                daa,
                ebit,
                ebitda,
                fcff,
                fcfe,
                current_exint,
                noncurrent_exint,
                interestdebt,
                netdebt,
                tangible_asset,
                working_capital,
                networking_capital,
                invest_capital,
                retained_earnings,
                diluted2_eps,
                bps,
                ocfps,
                retainedps,
                cfps,
                ebit_ps,
                fcff_ps,
                fcfe_ps,
                netprofit_margin,
                grossprofit_margin,
                cogs_of_sales,
                expense_of_sales,
                profit_to_gr,
                saleexp_to_gr,
                adminexp_of_gr,
                finaexp_of_gr,
                impai_ttm,
                gc_of_gr,
                op_of_gr,
                ebit_of_gr,
                roe,
                roe_waa,
                roe_dt,
                roa,
                npta,
                roic,
                roe_yearly,
                roa2_yearly,
                roe_avg,
                opincome_of_ebt,
                investincome_of_ebt,
                n_op_profit_of_ebt,
                tax_to_ebt,
                dtprofit_to_profit,
                salescash_to_or,
                ocf_to_or,
                ocf_to_opincome,
                capitalized_to_da,
                debt_to_assets,
                assets_to_eqt,
                dp_assets_to_eqt,
                ca_to_assets,
                nca_to_assets,
                tbassets_to_totalassets,
                int_to_talcap,
                eqt_to_talcapital,
                currentdebt_to_debt,
                longdeb_to_debt,
                ocf_to_shortdebt,
                debt_to_eqt,
                eqt_to_debt,
                eqt_to_interestdebt,
                tangibleasset_to_debt,
                tangasset_to_intdebt,
                tangibleasset_to_netdebt,
                ocf_to_debt,
                ocf_to_interestdebt,
                ocf_to_netdebt,
                ebit_to_interest,
                longdebt_to_workingcapital,
                ebitda_to_debt,
                turn_days,
                roa_yearly,
                roa_dp,
                fixed_assets,
                profit_prefin_exp,
                non_op_profit,
                op_to_ebt,
                nop_to_ebt,
                ocf_to_profit,
                cash_to_liqdebt,
                cash_to_liqdebt_withinterest,
                op_to_liqdebt,
                op_to_debt,
                roic_yearly,
                total_fa_trun,
                profit_to_op,
                q_opincome,
                q_investincome,
                q_dtprofit,
                q_eps,
                q_netprofit_margin,
                q_gsprofit_margin,
                q_exp_to_sales,
                q_profit_to_gr,
                q_saleexp_to_gr,
                q_adminexp_to_gr,
                q_finaexp_to_gr,
                q_impair_to_gr_ttm,
                q_gc_to_gr,
                q_op_to_gr,
                q_roe,
                q_dt_roe,
                q_npta,
                q_opincome_to_ebt,
                q_investincome_to_ebt,
                q_dtprofit_to_profit,
                q_salescash_to_or,
                q_ocf_to_sales,
                q_ocf_to_or,
                basic_eps_yoy,
                dt_eps_yoy,
                cfps_yoy,
                op_yoy,
                ebt_yoy,
                netprofit_yoy,
                dt_netprofit_yoy,
                ocf_yoy,
                roe_yoy,
                bps_yoy,
                assets_yoy,
                eqt_yoy,
                tr_yoy,
                or_yoy,
                q_gr_yoy,
                q_gr_qoq,
                q_sales_yoy,
                q_sales_qoq,
                q_op_yoy,
                q_op_qoq,
                q_profit_yoy,
                q_profit_qoq,
                q_netprofit_yoy,
                q_netprofit_qoq,
                equity_yoy,
                rd_exp,
                update_flag)
        COMMENT "tushare_沪深股票_财务数据_财务指标数据"

        DISTRIBUTED BY HASH(ts_code) BUCKETS 1
        PROPERTIES (
            "replication_num" = "1"
        );"""
    )
    doris_client.execute(operation)


@basis.basis_function.retry
def download_execute(
    pro,
    logger,
    ts_code="",
    ann_date="",
    start_date="",
    end_date="",
    period="",
    update_flag="",
    limit="",
    offset="",
):
    """执行具体下载操作"""
    exception_status = 0  # 0表示下载正常，1表示出现异常状况
    try:
        df = pro.fina_indicator_vip(
            **{
                "ts_code": ts_code,
                "ann_date": ann_date,
                "start_date": start_date,
                "end_date": end_date,
                "period": period,
                "update_flag": update_flag,
                "limit": limit,
                "offset": offset,
            },
            fields=[
                "ts_code",
                "ann_date",
                "end_date",
                "eps",
                "dt_eps",
                "total_revenue_ps",
                "revenue_ps",
                "capital_rese_ps",
                "surplus_rese_ps",
                "undist_profit_ps",
                "extra_item",
                "profit_dedt",
                "gross_margin",
                "current_ratio",
                "quick_ratio",
                "cash_ratio",
                "invturn_days",
                "arturn_days",
                "inv_turn",
                "ar_turn",
                "ca_turn",
                "fa_turn",
                "assets_turn",
                "op_income",
                "valuechange_income",
                "interst_income",
                "daa",
                "ebit",
                "ebitda",
                "fcff",
                "fcfe",
                "current_exint",
                "noncurrent_exint",
                "interestdebt",
                "netdebt",
                "tangible_asset",
                "working_capital",
                "networking_capital",
                "invest_capital",
                "retained_earnings",
                "diluted2_eps",
                "bps",
                "ocfps",
                "retainedps",
                "cfps",
                "ebit_ps",
                "fcff_ps",
                "fcfe_ps",
                "netprofit_margin",
                "grossprofit_margin",
                "cogs_of_sales",
                "expense_of_sales",
                "profit_to_gr",
                "saleexp_to_gr",
                "adminexp_of_gr",
                "finaexp_of_gr",
                "impai_ttm",
                "gc_of_gr",
                "op_of_gr",
                "ebit_of_gr",
                "roe",
                "roe_waa",
                "roe_dt",
                "roa",
                "npta",
                "roic",
                "roe_yearly",
                "roa2_yearly",
                "roe_avg",
                "opincome_of_ebt",
                "investincome_of_ebt",
                "n_op_profit_of_ebt",
                "tax_to_ebt",
                "dtprofit_to_profit",
                "salescash_to_or",
                "ocf_to_or",
                "ocf_to_opincome",
                "capitalized_to_da",
                "debt_to_assets",
                "assets_to_eqt",
                "dp_assets_to_eqt",
                "ca_to_assets",
                "nca_to_assets",
                "tbassets_to_totalassets",
                "int_to_talcap",
                "eqt_to_talcapital",
                "currentdebt_to_debt",
                "longdeb_to_debt",
                "ocf_to_shortdebt",
                "debt_to_eqt",
                "eqt_to_debt",
                "eqt_to_interestdebt",
                "tangibleasset_to_debt",
                "tangasset_to_intdebt",
                "tangibleasset_to_netdebt",
                "ocf_to_debt",
                "ocf_to_interestdebt",
                "ocf_to_netdebt",
                "ebit_to_interest",
                "longdebt_to_workingcapital",
                "ebitda_to_debt",
                "turn_days",
                "roa_yearly",
                "roa_dp",
                "fixed_assets",
                "profit_prefin_exp",
                "non_op_profit",
                "op_to_ebt",
                "nop_to_ebt",
                "ocf_to_profit",
                "cash_to_liqdebt",
                "cash_to_liqdebt_withinterest",
                "op_to_liqdebt",
                "op_to_debt",
                "roic_yearly",
                "total_fa_trun",
                "profit_to_op",
                "q_opincome",
                "q_investincome",
                "q_dtprofit",
                "q_eps",
                "q_netprofit_margin",
                "q_gsprofit_margin",
                "q_exp_to_sales",
                "q_profit_to_gr",
                "q_saleexp_to_gr",
                "q_adminexp_to_gr",
                "q_finaexp_to_gr",
                "q_impair_to_gr_ttm",
                "q_gc_to_gr",
                "q_op_to_gr",
                "q_roe",
                "q_dt_roe",
                "q_npta",
                "q_opincome_to_ebt",
                "q_investincome_to_ebt",
                "q_dtprofit_to_profit",
                "q_salescash_to_or",
                "q_ocf_to_sales",
                "q_ocf_to_or",
                "basic_eps_yoy",
                "dt_eps_yoy",
                "cfps_yoy",
                "op_yoy",
                "ebt_yoy",
                "netprofit_yoy",
                "dt_netprofit_yoy",
                "ocf_yoy",
                "roe_yoy",
                "bps_yoy",
                "assets_yoy",
                "eqt_yoy",
                "tr_yoy",
                "or_yoy",
                "q_gr_yoy",
                "q_gr_qoq",
                "q_sales_yoy",
                "q_sales_qoq",
                "q_op_yoy",
                "q_op_qoq",
                "q_profit_yoy",
                "q_profit_qoq",
                "q_netprofit_yoy",
                "q_netprofit_qoq",
                "equity_yoy",
                "rd_exp",
                "update_flag",
            ]
        )
    except:
        logger.error("An exception occurred")
        df = pandas.DataFrame()
        exception_status = 1  # 下载出现异常状况
    return df, exception_status


def download():
    """下载 沪深股票_财务数据_财务指标数据"""

    # 读取config/database.yaml
    config = basis.basis_function.load_config()

    # 下载数据存储的表格名称
    table_name = config["Ts_HuShenGuPiao_CaiWuShuJu_CaiWuZhiBiaoShuJu"]["table_name"]

    # 创建logger
    logger = basis.basis_function.creat_logger()

    # # 按公告日期下载
    # basis.basis_function.download_by_ann_date(table_name, download_execute, logger)

    # 按报告期下载
    basis.HuShunGuPiao_function.download_by_period(table_name, download_execute, logger)


if __name__ == "__main__":
    create_table()
    download()
