# -*- coding: utf-8 -*-
if __name__ == "__main__":
    import _in_folder_tools

import basis.with_pydoris
import basis.basis_function
import basis.HuShunGuPiao_function
import basis.with_pydoris
import pandas
import time

# https://tushare.pro/document/2?doc_id=36
# 默认的调取接口必须指定ts_code，在默认接口后加_vip则无需指定ts_code。
# *_vip接口需要5000积分才可调用。具体见上面链接。


# 创建表格
def create_table():
    # 连接database
    doris_client = basis.with_pydoris.connect_database()
    # 读取basis/config.yaml
    config = basis.basis_function.load_config()
    # 创建表格
    operation = (
        "CREATE TABLE IF NOT EXISTS "
        + config["database_name"]
        + "."
        + config["Ts_HuShenGuPiao_CaiWuShuJu_ZiChanFuZhaiBiao"]["table_name"]
        + """
        (
            ts_code VARCHAR(50) COMMENT "TS股票代码",
            ann_date VARCHAR(8) COMMENT "公告日期",
            f_ann_date VARCHAR(8) COMMENT "实际公告日期",
            end_date VARCHAR(8) COMMENT "报告期",
            report_type VARCHAR(2) COMMENT "报表类型",
            comp_type VARCHAR(1) COMMENT "公司类型(1一般工商业2银行3保险4证券)",
            end_type VARCHAR(8) COMMENT "报告期类型",
            total_share DECIMAL COMMENT "期末总股本",
            cap_rese DECIMAL COMMENT "资本公积金",
            undistr_porfit DECIMAL COMMENT "未分配利润",
            surplus_rese DECIMAL COMMENT "盈余公积金",
            special_rese DECIMAL COMMENT "专项储备",
            money_cap DECIMAL COMMENT "货币资金",
            trad_asset DECIMAL COMMENT "交易性金融资产",
            notes_receiv DECIMAL COMMENT "应收票据",
            accounts_receiv DECIMAL COMMENT "应收账款",
            oth_receiv DECIMAL COMMENT "其他应收款",
            prepayment DECIMAL COMMENT "预付款项",
            div_receiv DECIMAL COMMENT "应收股利",
            int_receiv DECIMAL COMMENT "应收利息",
            inventories DECIMAL COMMENT "存货",
            amor_exp DECIMAL COMMENT "长期待摊费用",
            nca_within_1y DECIMAL COMMENT "一年内到期的非流动资产",
            sett_rsrv DECIMAL COMMENT "结算备付金",
            loanto_oth_bank_fi DECIMAL COMMENT "拆出资金",
            premium_receiv DECIMAL COMMENT "应收保费",
            reinsur_receiv DECIMAL COMMENT "应收分保账款",
            reinsur_res_receiv DECIMAL COMMENT "应收分保合同准备金",
            pur_resale_fa DECIMAL COMMENT "买入返售金融资产",
            oth_cur_assets DECIMAL COMMENT "其他流动资产",
            total_cur_assets DECIMAL COMMENT "流动资产合计",
            fa_avail_for_sale DECIMAL COMMENT "可供出售金融资产",
            htm_invest DECIMAL COMMENT "持有至到期投资",
            lt_eqt_invest DECIMAL COMMENT "长期股权投资",
            invest_real_estate DECIMAL COMMENT "投资性房地产",
            time_deposits DECIMAL COMMENT "定期存款",
            oth_assets DECIMAL COMMENT "其他资产",
            lt_rec DECIMAL COMMENT "长期应收款",
            fix_assets DECIMAL COMMENT "固定资产",
            cip DECIMAL COMMENT "在建工程",
            const_materials DECIMAL COMMENT "工程物资",
            fixed_assets_disp DECIMAL COMMENT "固定资产清理",
            produc_bio_assets DECIMAL COMMENT "生产性生物资产",
            oil_and_gas_assets DECIMAL COMMENT "油气资产",
            intan_assets DECIMAL COMMENT "无形资产",
            r_and_d DECIMAL COMMENT "研发支出",
            goodwill DECIMAL COMMENT "商誉",
            lt_amor_exp DECIMAL COMMENT "长期待摊费用",
            defer_tax_assets DECIMAL COMMENT "递延所得税资产",
            decr_in_disbur DECIMAL COMMENT "发放贷款及垫款",
            oth_nca DECIMAL COMMENT "其他非流动资产",
            total_nca DECIMAL COMMENT "非流动资产合计",
            cash_reser_cb DECIMAL COMMENT "现金及存放中央银行款项",
            depos_in_oth_bfi DECIMAL COMMENT "存放同业和其它金融机构款项",
            prec_metals DECIMAL COMMENT "贵金属",
            deriv_assets DECIMAL COMMENT "衍生金融资产",
            rr_reins_une_prem DECIMAL COMMENT "应收分保未到期责任准备金",
            rr_reins_outstd_cla DECIMAL COMMENT "应收分保未决赔款准备金",
            rr_reins_lins_liab DECIMAL COMMENT "应收分保寿险责任准备金",
            rr_reins_lthins_liab DECIMAL COMMENT "应收分保长期健康险责任准备金",
            refund_depos DECIMAL COMMENT "存出保证金",
            ph_pledge_loans DECIMAL COMMENT "保户质押贷款",
            refund_cap_depos DECIMAL COMMENT "存出资本保证金",
            indep_acct_assets DECIMAL COMMENT "独立账户资产",
            client_depos DECIMAL COMMENT "其中：客户资金存款",
            client_prov DECIMAL COMMENT "其中：客户备付金",
            transac_seat_fee DECIMAL COMMENT "其中:交易席位费",
            invest_as_receiv DECIMAL COMMENT "应收款项类投资",
            total_assets DECIMAL COMMENT "资产总计",
            lt_borr DECIMAL COMMENT "长期借款",
            st_borr DECIMAL COMMENT "短期借款",
            cb_borr DECIMAL COMMENT "向中央银行借款",
            depos_ib_deposits DECIMAL COMMENT "吸收存款及同业存放",
            loan_oth_bank DECIMAL COMMENT "拆入资金",
            trading_fl DECIMAL COMMENT "交易性金融负债",
            notes_payable DECIMAL COMMENT "应付票据",
            acct_payable DECIMAL COMMENT "应付账款",
            adv_receipts DECIMAL COMMENT "预收款项",
            sold_for_repur_fa DECIMAL COMMENT "卖出回购金融资产款",
            comm_payable DECIMAL COMMENT "应付手续费及佣金",
            payroll_payable DECIMAL COMMENT "应付职工薪酬",
            taxes_payable DECIMAL COMMENT "应交税费",
            int_payable DECIMAL COMMENT "应付利息",
            div_payable DECIMAL COMMENT "应付股利",
            oth_payable DECIMAL COMMENT "其他应付款",
            acc_exp DECIMAL COMMENT "预提费用",
            deferred_inc DECIMAL COMMENT "递延收益",
            st_bonds_payable DECIMAL COMMENT "应付短期债券",
            payable_to_reinsurer DECIMAL COMMENT "应付分保账款",
            rsrv_insur_cont DECIMAL COMMENT "保险合同准备金",
            acting_trading_sec DECIMAL COMMENT "代理买卖证券款",
            acting_uw_sec DECIMAL COMMENT "代理承销证券款",
            non_cur_liab_due_1y DECIMAL COMMENT "一年内到期的非流动负债",
            oth_cur_liab DECIMAL COMMENT "其他流动负债",
            total_cur_liab DECIMAL COMMENT "流动负债合计",
            bond_payable DECIMAL COMMENT "应付债券",
            lt_payable DECIMAL COMMENT "长期应付款",
            specific_payables DECIMAL COMMENT "专项应付款",
            estimated_liab DECIMAL COMMENT "预计负债",
            defer_tax_liab DECIMAL COMMENT "递延所得税负债",
            defer_inc_non_cur_liab DECIMAL COMMENT "递延收益-非流动负债",
            oth_ncl DECIMAL COMMENT "其他非流动负债",
            total_ncl DECIMAL COMMENT "非流动负债合计",
            depos_oth_bfi DECIMAL COMMENT "同业和其它金融机构存放款项",
            deriv_liab DECIMAL COMMENT "衍生金融负债",
            depos DECIMAL COMMENT "吸收存款",
            agency_bus_liab DECIMAL COMMENT "代理业务负债",
            oth_liab DECIMAL COMMENT "其他负债",
            prem_receiv_adva DECIMAL COMMENT "预收保费",
            depos_received DECIMAL COMMENT "存入保证金",
            ph_invest DECIMAL COMMENT "保户储金及投资款",
            reser_une_prem DECIMAL COMMENT "未到期责任准备金",
            reser_outstd_claims DECIMAL COMMENT "未决赔款准备金",
            reser_lins_liab DECIMAL COMMENT "寿险责任准备金",
            reser_lthins_liab DECIMAL COMMENT "长期健康险责任准备金",
            indept_acc_liab DECIMAL COMMENT "独立账户负债",
            pledge_borr DECIMAL COMMENT "其中:质押借款",
            indem_payable DECIMAL COMMENT "应付赔付款",
            policy_div_payable DECIMAL COMMENT "应付保单红利",
            total_liab DECIMAL COMMENT "负债合计",
            treasury_share DECIMAL COMMENT "减:库存股",
            ordin_risk_reser DECIMAL COMMENT "一般风险准备",
            forex_differ DECIMAL COMMENT "外币报表折算差额",
            invest_loss_unconf DECIMAL COMMENT "未确认的投资损失",
            minority_int DECIMAL COMMENT "少数股东权益",
            total_hldr_eqy_exc_min_int DECIMAL COMMENT "股东权益合计(不含少数股东权益)",
            total_hldr_eqy_inc_min_int DECIMAL COMMENT "股东权益合计(含少数股东权益)",
            total_liab_hldr_eqy DECIMAL COMMENT "负债及股东权益总计",
            lt_payroll_payable DECIMAL COMMENT "长期应付职工薪酬",
            oth_comp_income DECIMAL COMMENT "其他综合收益",
            oth_eqt_tools DECIMAL COMMENT "其他权益工具",
            oth_eqt_tools_p_shr DECIMAL COMMENT "其他权益工具(优先股)",
            lending_funds DECIMAL COMMENT "融出资金",
            acc_receivable DECIMAL COMMENT "应收款项",
            st_fin_payable DECIMAL COMMENT "应付短期融资款",
            payables DECIMAL COMMENT "应付款项",
            hfs_assets DECIMAL COMMENT "持有待售的资产",
            hfs_sales DECIMAL COMMENT "持有待售的负债",
            cost_fin_assets DECIMAL COMMENT "以摊余成本计量的金融资产",
            fair_value_fin_assets DECIMAL COMMENT "以公允价值计量且其变动计入其他综合收益的金融资产",
            contract_assets DECIMAL COMMENT "合同资产",
            contract_liab DECIMAL COMMENT "合同负债",
            accounts_receiv_bill DECIMAL COMMENT "应收票据及应收账款",
            accounts_pay DECIMAL COMMENT "应付票据及应付账款",
            oth_rcv_total DECIMAL COMMENT "其他应收款(合计)（元）",
            fix_assets_total DECIMAL COMMENT "固定资产(合计)(元)",
            cip_total DECIMAL COMMENT "在建工程(合计)(元)",
            oth_pay_total DECIMAL COMMENT "其他应付款(合计)(元)",
            long_pay_total DECIMAL COMMENT "长期应付款(合计)(元)",
            debt_invest DECIMAL COMMENT "债权投资(元)",
            oth_debt_invest DECIMAL COMMENT "其他债权投资(元)",
            oth_eq_invest DECIMAL COMMENT "其他权益工具投资(元)",
            oth_illiq_fin_assets DECIMAL COMMENT "其他非流动金融资产(元)",
            oth_eq_ppbond DECIMAL COMMENT "其他权益工具:永续债(元)",
            receiv_financing DECIMAL COMMENT "应收款项融资",
            use_right_assets DECIMAL COMMENT "使用权资产",
            lease_liab DECIMAL COMMENT "租赁负债",
            update_flag VARCHAR(1) COMMENT "更新标识",            
        )
        UNIQUE KEY(ts_code,
                    ann_date,
                    f_ann_date,
                    end_date,
                    report_type,
                    comp_type,
                    end_type,
                    total_share,
                    cap_rese,
                    undistr_porfit,
                    surplus_rese,
                    special_rese,
                    money_cap,
                    trad_asset,
                    notes_receiv,
                    accounts_receiv,
                    oth_receiv,
                    prepayment,
                    div_receiv,
                    int_receiv,
                    inventories,
                    amor_exp,
                    nca_within_1y,
                    sett_rsrv,
                    loanto_oth_bank_fi,
                    premium_receiv,
                    reinsur_receiv,
                    reinsur_res_receiv,
                    pur_resale_fa,
                    oth_cur_assets,
                    total_cur_assets,
                    fa_avail_for_sale,
                    htm_invest,
                    lt_eqt_invest,
                    invest_real_estate,
                    time_deposits,
                    oth_assets,
                    lt_rec,
                    fix_assets,
                    cip,
                    const_materials,
                    fixed_assets_disp,
                    produc_bio_assets,
                    oil_and_gas_assets,
                    intan_assets,
                    r_and_d,
                    goodwill,
                    lt_amor_exp,
                    defer_tax_assets,
                    decr_in_disbur,
                    oth_nca,
                    total_nca,
                    cash_reser_cb,
                    depos_in_oth_bfi,
                    prec_metals,
                    deriv_assets,
                    rr_reins_une_prem,
                    rr_reins_outstd_cla,
                    rr_reins_lins_liab,
                    rr_reins_lthins_liab,
                    refund_depos,
                    ph_pledge_loans,
                    refund_cap_depos,
                    indep_acct_assets,
                    client_depos,
                    client_prov,
                    transac_seat_fee,
                    invest_as_receiv,
                    total_assets,
                    lt_borr,
                    st_borr,
                    cb_borr,
                    depos_ib_deposits,
                    loan_oth_bank,
                    trading_fl,
                    notes_payable,
                    acct_payable,
                    adv_receipts,
                    sold_for_repur_fa,
                    comm_payable,
                    payroll_payable,
                    taxes_payable,
                    int_payable,
                    div_payable,
                    oth_payable,
                    acc_exp,
                    deferred_inc,
                    st_bonds_payable,
                    payable_to_reinsurer,
                    rsrv_insur_cont,
                    acting_trading_sec,
                    acting_uw_sec,
                    non_cur_liab_due_1y,
                    oth_cur_liab,
                    total_cur_liab,
                    bond_payable,
                    lt_payable,
                    specific_payables,
                    estimated_liab,
                    defer_tax_liab,
                    defer_inc_non_cur_liab,
                    oth_ncl,
                    total_ncl,
                    depos_oth_bfi,
                    deriv_liab,
                    depos,
                    agency_bus_liab,
                    oth_liab,
                    prem_receiv_adva,
                    depos_received,
                    ph_invest,
                    reser_une_prem,
                    reser_outstd_claims,
                    reser_lins_liab,
                    reser_lthins_liab,
                    indept_acc_liab,
                    pledge_borr,
                    indem_payable,
                    policy_div_payable,
                    total_liab,
                    treasury_share,
                    ordin_risk_reser,
                    forex_differ,
                    invest_loss_unconf,
                    minority_int,
                    total_hldr_eqy_exc_min_int,
                    total_hldr_eqy_inc_min_int,
                    total_liab_hldr_eqy,
                    lt_payroll_payable,
                    oth_comp_income,
                    oth_eqt_tools,
                    oth_eqt_tools_p_shr,
                    lending_funds,
                    acc_receivable,
                    st_fin_payable,
                    payables,
                    hfs_assets,
                    hfs_sales,
                    cost_fin_assets,
                    fair_value_fin_assets,
                    contract_assets,
                    contract_liab,
                    accounts_receiv_bill,
                    accounts_pay,
                    oth_rcv_total,
                    fix_assets_total,
                    cip_total,
                    oth_pay_total,
                    long_pay_total,
                    debt_invest,
                    oth_debt_invest,
                    oth_eq_invest,
                    oth_illiq_fin_assets,
                    oth_eq_ppbond,
                    receiv_financing,
                    use_right_assets,
                    lease_liab,
                    update_flag)
        COMMENT "tushare_沪深股票_财务数据_资产负债表"

        DISTRIBUTED BY HASH(ts_code) BUCKETS 1
        PROPERTIES (
            "replication_num" = "1"
        );"""
    )
    doris_client.execute(operation)


@basis.basis_function.retry
def download_execute(
    pro,
    logger,
    ts_code="",
    ann_date="",
    f_ann_date="",
    start_date="",
    end_date="",
    period="",
    report_type="",
    comp_type="",
    limit=8000,
    offset="",
):
    """执行具体下载操作"""
    # 读取config/database.yaml
    config = basis.basis_function.load_config()
    exception_status = 0  # 0表示下载正常，1表示出现异常状况
    try:
        df = pandas.DataFrame()  # 最终函数的返回值
        df_local = pandas.DataFrame()  # 暂时设为空值，以执行循环
        num_times_download = 0  # 已经下载了几次
        # 若首次下载，或下载的数据大于等于limit，继续循环
        while num_times_download == 0 or df_local.shape[0] >= limit:
            df_local = pro.balancesheet_vip(
                **{
                    "ts_code": ts_code,
                    "ann_date": ann_date,
                    "f_ann_date": f_ann_date,
                    "start_date": start_date,
                    "end_date": end_date,
                    "period": period,
                    "report_type": report_type,
                    "comp_type": comp_type,
                    "limit": limit,
                    "offset": offset,
                },
                fields=[
                    "ts_code",
                    "ann_date",
                    "f_ann_date",
                    "end_date",
                    "report_type",
                    "comp_type",
                    "end_type",
                    "total_share",
                    "cap_rese",
                    "undistr_porfit",
                    "surplus_rese",
                    "special_rese",
                    "money_cap",
                    "trad_asset",
                    "notes_receiv",
                    "accounts_receiv",
                    "oth_receiv",
                    "prepayment",
                    "div_receiv",
                    "int_receiv",
                    "inventories",
                    "amor_exp",
                    "nca_within_1y",
                    "sett_rsrv",
                    "loanto_oth_bank_fi",
                    "premium_receiv",
                    "reinsur_receiv",
                    "reinsur_res_receiv",
                    "pur_resale_fa",
                    "oth_cur_assets",
                    "total_cur_assets",
                    "fa_avail_for_sale",
                    "htm_invest",
                    "lt_eqt_invest",
                    "invest_real_estate",
                    "time_deposits",
                    "oth_assets",
                    "lt_rec",
                    "fix_assets",
                    "cip",
                    "const_materials",
                    "fixed_assets_disp",
                    "produc_bio_assets",
                    "oil_and_gas_assets",
                    "intan_assets",
                    "r_and_d",
                    "goodwill",
                    "lt_amor_exp",
                    "defer_tax_assets",
                    "decr_in_disbur",
                    "oth_nca",
                    "total_nca",
                    "cash_reser_cb",
                    "depos_in_oth_bfi",
                    "prec_metals",
                    "deriv_assets",
                    "rr_reins_une_prem",
                    "rr_reins_outstd_cla",
                    "rr_reins_lins_liab",
                    "rr_reins_lthins_liab",
                    "refund_depos",
                    "ph_pledge_loans",
                    "refund_cap_depos",
                    "indep_acct_assets",
                    "client_depos",
                    "client_prov",
                    "transac_seat_fee",
                    "invest_as_receiv",
                    "total_assets",
                    "lt_borr",
                    "st_borr",
                    "cb_borr",
                    "depos_ib_deposits",
                    "loan_oth_bank",
                    "trading_fl",
                    "notes_payable",
                    "acct_payable",
                    "adv_receipts",
                    "sold_for_repur_fa",
                    "comm_payable",
                    "payroll_payable",
                    "taxes_payable",
                    "int_payable",
                    "div_payable",
                    "oth_payable",
                    "acc_exp",
                    "deferred_inc",
                    "st_bonds_payable",
                    "payable_to_reinsurer",
                    "rsrv_insur_cont",
                    "acting_trading_sec",
                    "acting_uw_sec",
                    "non_cur_liab_due_1y",
                    "oth_cur_liab",
                    "total_cur_liab",
                    "bond_payable",
                    "lt_payable",
                    "specific_payables",
                    "estimated_liab",
                    "defer_tax_liab",
                    "defer_inc_non_cur_liab",
                    "oth_ncl",
                    "total_ncl",
                    "depos_oth_bfi",
                    "deriv_liab",
                    "depos",
                    "agency_bus_liab",
                    "oth_liab",
                    "prem_receiv_adva",
                    "depos_received",
                    "ph_invest",
                    "reser_une_prem",
                    "reser_outstd_claims",
                    "reser_lins_liab",
                    "reser_lthins_liab",
                    "indept_acc_liab",
                    "pledge_borr",
                    "indem_payable",
                    "policy_div_payable",
                    "total_liab",
                    "treasury_share",
                    "ordin_risk_reser",
                    "forex_differ",
                    "invest_loss_unconf",
                    "minority_int",
                    "total_hldr_eqy_exc_min_int",
                    "total_hldr_eqy_inc_min_int",
                    "total_liab_hldr_eqy",
                    "lt_payroll_payable",
                    "oth_comp_income",
                    "oth_eqt_tools",
                    "oth_eqt_tools_p_shr",
                    "lending_funds",
                    "acc_receivable",
                    "st_fin_payable",
                    "payables",
                    "hfs_assets",
                    "hfs_sales",
                    "cost_fin_assets",
                    "fair_value_fin_assets",
                    "contract_assets",
                    "contract_liab",
                    "accounts_receiv_bill",
                    "accounts_pay",
                    "oth_rcv_total",
                    "fix_assets_total",
                    "cip_total",
                    "oth_pay_total",
                    "long_pay_total",
                    "debt_invest",
                    "oth_debt_invest",
                    "oth_eq_invest",
                    "oth_illiq_fin_assets",
                    "oth_eq_ppbond",
                    "receiv_financing",
                    "use_right_assets",
                    "lease_liab",
                    "update_flag",
                ]
            )  # 从tushare下载
            num_times_download += 1  # 已经下载了几次
            df = pandas.concat([df, df_local])  # 将df_local加入结果
            offset = num_times_download * limit  # 计算新的offset
            time.sleep(config["regular_gap"])  # 等待一段时间再继续下载
    except:
        logger.error("An exception occurred")
        df = pandas.DataFrame()
        exception_status = 1  # 下载出现异常状况
    return df, exception_status


def download():
    """下载 沪深股票_财务数据_资产负债表"""

    # 读取config/database.yaml
    config = basis.basis_function.load_config()

    # 下载数据存储的表格名称
    table_name = config["Ts_HuShenGuPiao_CaiWuShuJu_ZiChanFuZhaiBiao"]["table_name"]

    # 创建logger
    logger = basis.basis_function.creat_logger()

    # 按报告期下载
    # 报告类型 1合并报表 2单季合并 3调整单季合并表 4调整合并报表 5调整前合并报表 6母公司报表 7母公司单季表 8 母公司调整单季表 9母公司调整表 10母公司调整前报表 11调整前合并报表 12母公司调整前报表
    for report_type in range(1, 13):
        basis.HuShunGuPiao_function.download_financial_statement_by_period(
            table_name, download_execute, report_type, logger
        )


if __name__ == "__main__":
    create_table()
    download()
